Application
Burkut60/Burkut-android pull request #3
Opened 2020-03-04 21:00 UTC by Burkut60

Все тупик, второй день бьюсь. Кажется логику понимаю, реализовать не могу.

2020-03-05 15:55 UTC, tim-teacher requested changes

2020-03-05 15:55 UTC, tim-teacher commented on out/production/Burkut-android/Application/AllNews.java
> +public class AllNews {
Что за название AllNews? У тебя тут один класс, которые представляет одну единицу данных, тоесть одну новость. Если б тут у тебя массив лежал, тогда понятно название.
Поменяй на просто News

2020-03-05 15:55 UTC, tim-teacher commented on out/production/Burkut-android/Application/File_download.java
> +        URL newUrl = new URL("https://fake-api.kiparo.by/json/it_news.json");
ссылку нужно вынести в переменную константы - public static final

2020-03-05 15:55 UTC, tim-teacher commented on out/production/Burkut-android/Application/InPut.java
> +
ода строка лишняя - тоесть прелом поменьше нужно

2020-03-05 15:55 UTC, tim-teacher commented on out/production/Burkut-android/Application/InPut.java
> +        public static void getPut(URL b) throws IOException {
что за магическая переменная с именем b не понятно :)

2020-03-05 15:55 UTC, tim-teacher commented on out/production/Burkut-android/Application/InPut.java
> +
опять пробелы лишние

2020-03-05 15:55 UTC, tim-teacher commented on out/production/Burkut-android/Application/UtilJson.java
> +       AllNews ne = gson.fromJson(jsonString ,AllNews.class);
Эм, у тебя же List новостей должен быть на выходе, а не одна новость

2020-03-05 15:55 UTC, tim-teacher commented on out/production/Burkut-android/Dz_0.java
> +    static void isAnagram(String a, String b) {
А анаграмма каким боком тут прилетела? )

2020-03-05 15:55 UTC, tim-teacher commented on out/production/Burkut-android/Dz_0.java
> +    static void isAnagram(String a, String b) {
имею ввиду в этом коммите

2020-03-07 14:45 UTC, Burkut60 commented
Зашел в тупик.

2020-03-09 22:34 UTC, merged